CREATE TABLE IF NOT EXISTS owner
(
    name character varying COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT owner_pkey PRIMARY KEY (id)
);